### ISSUE TITLE
[Discussion] Which bodies should have NaturalArmor

### ISSUE THREAD

**Issue by Juanfrank** [Breadbox2k19/Geraldo-s-Wild-Hunt#1]
This is the list of Bodies:

Rock Humanoid - Yes
Wisp - I don't think so, maybe damage reduction?
Single Eyed Humanoid (I believe cyclops) - No?
Winged Reptile - Maybe Wyverns
Winged Bird - Depends
QuadrupedwithPawsandHorns - Depends
Horned Humanoid - Horns perhaps, it really depends on which creature it is
JellyFish - Nein?

I've always believed races deserve the hasNaturalArmor when they have even a single part that could be armored (ex. claws, horns, etc.) so that these parts play a factor in overall damage taken and since they're attack tools, so they don't get broken as easily.

**Comment by Breadbox2k19** [comment]
Basically the creatures with any assigned armour should get armour coverage. I don’t decide which creature should gets armour, the original mod author already did.
I’ll take a closer look tomorrow.

**Comment by Juanfrank** [comment]
Yeah, this is just an initial issue so we can later decide which parts of these Bodies should have the NaturalArmor attached to them.

For instance Rock Humanoids might have armor in their head, arms, etc., but maybe not in their eyes.

**Comment by Breadbox2k19** [comment]
I can confirm that the following bodies would need armour coverage: 
WMH_Bird
WMH_JellyfishBody
WMH_SingleEyedHumanoid
WMH_RockHumanoid
WMH_Reptile

**Comment by Juanfrank** [comment]
Addressed by #2
